### PR TITLE
Opened Accordions uses suitable image part

### PR DESCRIPTION
**Pull request by Minei3oat**
Now the opened accordions are using the image part with the "x" instead
those with the "+".

### CODE REVIEW

**Comment by Bakual** [comment]
I'm not sure what you mean. The closed ones have the "+" and the open ones have the red "X". I think it was always like this.

**Comment by Bakual** [comment]
Ah crap, I see what you mean now. It works in http://www.bakual.net/dokumentation/typography.html where I use the Sliders extension but it doesn't in http://www.bakual.net/kontakt.html.

**Comment by Minei3oat** [comment]
The JavaScript could be replaced by a few lines PHP-Code in JHTMLBootstrap, like it is done there with the in-class of the accordion-body: https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/bootstrap.php#L672-L689

**Comment by Bakual** [comment]
It indeed looks like a Joomla bug that initially the `collapsed` class is missing.
You want to open an issue there or should I do it? :smile:

**Comment by Minei3oat** [comment]
I've created a pull request :smile:
https://github.com/joomla/joomla-cms/pull/11859

**Comment by Bakual** [comment]
Did at the same time :smile: 
Closed mine now.

**Comment by Bakual** [comment]
https://github.com/Bakual/Allrounder/commit/b7e2300f0dddb606b5631937a98398c331dc367e should fix the issue in the template once your PR is merged.

**Comment by Minei3oat** [comment]
No, this wouldn't work, because closed slides are tagged with the class collapsed, but at position -60px there is the x which is needed for opened sliders.

But if you drop the changes made to the effects.js this pull request should work.

Because there is no special class for opened slides the style for opened slides must be the "normal" style. After that you kann declare the style for the closed ones with .collapsed which overrides the previous styles.

**Comment by Bakual** [comment]
True enough, I need the opposite :+1:

**Comment by Bakual** [comment]
Unfortunately your PR didn't play nice with the sliders from RegularLabs (which I use here: http://www.bakual.net/dokumentation/typography.html). I went another route: https://github.com/Bakual/Allrounder/commit/81b55b4514df102cc42aae4f53bd8e27a95e3a08 which seems to work now.

**Comment by Minei3oat** [comment]
The plugin is the problem.
The plugin writes the full path to the `href`-attribute of the `accordion-toggle,`, which prevents bootstrap to localize the `accordion-body`.

**Comment by Bakual** [comment]
I think the sliders plugin uses its own JavaScript.

**Comment by Minei3oat** [comment]
I looked over the code in the JS-File which is included and found nothing that adds/removes the in-class of the accordion-body. IMHO they uses the Bootstrap-Siders. I've looked at the rest of the plugin. They load Bootstrap and there is an language-string:
`RL_BOOTSTRAP_FRAMEWORK_DISABLED="You have disabled the Bootstrap Framework to be initiated. %s needs the Bootstrap Framework to function. Make sure your template or other extensions load the necessary scripts to replace the required functionality."`

**Comment by Bakual** [comment]
Hmm I don't know how it's done, but it certainly acts different from the contacts form. The Sliders plugin adds an `active` class to the parent `accordion-group` <div> which makes it quite good to style everything but it doesn't add the `collapsed` class to the header. It however also adds the `in` class to the body.

Anyway, the real difference is that the plugin does add a class when it is expanded and the native Joomla one when it is collapsed. Which makes one or the other need a `:not()` selector anyway :smile:

**Comment by Minei3oat** [comment]
The plugin adds the `active` class to the parent `accordion-group`.
Bootstrap adds the `in` class to the `accordion-body`. But Bootstrap isn't able to add the `collapsed` class to the `accordion-toggle` because the `href` attribute of the `accordion-toggle` is like `http://my-site.com/path/to/page#id` but bootstrap needs it like `#id`. Because of that Bootstrap cannot add the `collapsed` class to the àccordion-toggle` which depends on the `in` class of the referenzed element.

**Comment by Bakual** [comment]
Ah, but that's not something we can change in that plugin :)

**Comment by Minei3oat** [comment]
Yes, that must do the publisher of the plugin.

**Comment by zero-24** [comment]
>Unfortunately your PR didn't play nice with the sliders from RegularLabs 

@bakual this means we have broken regularLabs with the commit of that pr into the core?

**Comment by Bakual** [comment]
@zero-24 Nope. The Sliders plugin doesn't use the collapsed class. It works with a different class (`active`) on a different element.
The PR also doesn't introduce a new class, it only applies it consistently now.

**Comment by zero-24** [comment]
Ok i just want to be sure we dont need a fast 3.6.4 than :)

**Comment by Bakual** [comment]
> Ok i just want to be sure we dont need a fast 3.6.4 than :)

At least not because of that PR :)

**Comment by Minei3oat** [comment]
I've did some more research on that plugin. The full URL in the `href` Attribute of `accordion-toggle` seems not to be the problem. Bootstrap can handle that.
The Problem seems to be in the JavaScript of that plugin.
If I comment lines 485-491 in script.js of the plugin all works well.

**Comment by Bakual** [comment]
Is ee you opened a bug report at RegularLabs. Lets see what Peter knows :)

**Comment by Minei3oat** [comment]
Since Peter has fixed this issue the extra code for his Sliders can be safely removed 😄 .

**Comment by Bakual** [comment]
Merged and fixed a small error in it with https://github.com/Bakual/Allrounder/commit/2d90682db66c910606a9092a5c0052d05ef31dc7

Thanks :+1:

**Pull request merged**
