### PR TITLE
Compile customCssCode in templateX.css

### PR DESCRIPTION
**Pull request by Minei3oat**
This PR changes the treatment of the CSS-Code entered in the `customCssCode` form field. Now it will be added to the LESS-Code from the files and then be compiled by JLess. This makes it possible to enter all characters and LESS-Code in this form field.

Due to compatibility reasons the names of the form fields are the old ones. With new ones the previous settings would be lost.

### CODE REVIEW

**Comment by Bakual** [comment]
This would not be backward compatible as you would have to save the style after an update or you loose the custom CSS parameter on your site.

I honestly don't remember why I have not included that parameter in the compiled CSS.

Also, you move the file loading before the variable injections. Does that work? I would assume the variables have to be defined before they are used in the files. But haven't tested that :)

**Comment by Minei3oat** [comment]
The files are loaded into a string, which is used after the variable injections. And setting the base path, imho tells the compiler where to look for needed files but doesn't load files. So the move of the variable injections shouldn't be a problem.

One solution would be to left the old code in the index.php or to automatically regenerate all css-files on update.
Another would be to add this feature for a Joomla 4 release as then there are a lot of backward compatibility breaks such as Bootstrap 4 which requires to regenerate all css-files.

**Comment by Bakual** [comment]
> The files are loaded into a string, which is used after the variable injections. 

Ah true, we only use that later.

> Another would be to add this feature for a Joomla 4 release

For J4, we need to rethink/redo the whole template anyway. It's not only Bootstrap 4, it's also a move away from LESS files to SCSS. There exists a compiler from the same guy (https://github.com/leafo/scssphp) but it's to early anyway to look into J4 templates.

We could release a new major version of the LESS Allrounder, but I'm not sure if it is worth it.

**Comment by Minei3oat** [comment]
Maybe the best solution would be to recompile all `templateX.css`-files on update automatically. This would improve the propagation of fixes as now the fix is only propagated if the user saves the template style, which maybe happens first after several months/years.

**Comment by Bakual** [comment]
I'm not so keen on compiling the CSS during updates. Updates take some time already depending on the amount of updates the user does at the same time. Compiling usually is rather slow, and it would have to be done for each Allrounder style. I don't want people getting timeouts just because they update.
Besides compiling only works when the plugin is enabled.

While I like the idea of this PR, I probably leave it for 4.0. I don't think it's worth the trouble before that.

**Comment by Bakual** [comment]
I'm closing this as for 4.0 I have to get everything working without LESS and compiling anyway.

**Pull request closed without merging**
